nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200'] # Remplacez par l'URL de votre frontend Angular
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/': # Active CORS pour toutes les routes
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600
